DEFAULT_TAXONOMY_PATH = "taxonomy"
DEFAULT_API_KEY = "no_api_key"
DEFAULT_NUM_CPUS = 10
DEFAULT_TAXONOMY_BASE = "origin/main"
DEFAULT_OUT_DIR = "train-output"
DEFAULT_PROMPT_FILE = "prompt.txt"
DEFAULT_CHUNK_WORD_COUNT = 500
MAX_CONTEXT_SIZE = 8200
